"""
pystoch.utilities.exceptions
----------------------------

"""

class TraceInvalidatedException(Exception):
    pass

